name: rclone 
base: core24
adopt-info: rclone
summary: rsync for cloud storage
description: |
  Rclone ("rsync for cloud storage") is a command-line program to sync files and directories to and from different cloud storage providers.


  Please note that this is a community-maintained package. Use at your own risk.

  Due to the strict permissions control of Snap, some features may not work.

platforms:
  amd64:
  arm64:
  armhf:

grade: stable
confinement: strict

apps:
  rclone:
    command: bin/rclone
    completer: bin/rclone-completion.bash
    plugs:
      - home
      - network
      - network-bind
      - removable-media

parts:
  rclone:
    plugin: go
    build-snaps:
      - go
    source-type: git
    source: https://github.com/rclone/rclone
    source-tag: 'v1.71.1'
    source-depth: 1
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | tr -d 'v')
    build-environment:
      - CGO_ENABLED: 0
      - GOTAGS: snap
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      cd $CRAFT_PART_SRC
      make
      cp $(go env GOPATH)/bin/rclone $CRAFT_PART_INSTALL/bin/
      # generate bash completion
      $CRAFT_PART_INSTALL/bin/rclone completion bash $CRAFT_PART_INSTALL/bin/rclone-completion.bash
